// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	groupApplyFieldNames          = builder.RawFieldNames(&GroupApply{})
	groupApplyRows                = strings.Join(groupApplyFieldNames, ",")
	groupApplyRowsExpectAutoSet   = strings.Join(stringx.Remove(groupApplyFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	groupApplyRowsWithPlaceHolder = strings.Join(stringx.Remove(groupApplyFieldNames, "`apply_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGroupApplyApplyIdPrefix = "cache:groupApply:applyId:"
)

type (
	groupApplyModel interface {
		Insert(ctx context.Context, data *GroupApply) (sql.Result, error)
		FindOne(ctx context.Context, applyId string) (*GroupApply, error)
		Update(ctx context.Context,session sqlx.Session, data *GroupApply) error
		Delete(ctx context.Context, applyId string) error
		InsertByTargetIdList(ctx context.Context,session sqlx.Session,data ...*GroupApply) (sql.Result, error)
		Transx(ctx context.Context,fn func(ctx context.Context, session sqlx.Session) error) error
	}

	defaultGroupApplyModel struct {
		sqlc.CachedConn
		table string
	}

	GroupApply struct {
		ApplyId     string    `db:"apply_id"`     // 申请ID
		ApplicantId string    `db:"applicant_id"` // 申请人ID
		TargetId    string    `db:"target_id"`    // 目标用户ID
		GreetMsg    string    `db:"greet_msg"`    // 打招呼消息
		Status      int64     `db:"status"`       // 状态 (0:待处理, 1:同意, 2:拒绝)
		CreatedAt   time.Time `db:"created_at"`   // 申请时间
	}
)

func newGroupApplyModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultGroupApplyModel {
	return &defaultGroupApplyModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`group_apply`",
	}
}
func (m *defaultGroupApplyModel) Transx(ctx context.Context,fn func(ctx context.Context, session sqlx.Session) error) error{
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}
func (m *defaultGroupApplyModel) Delete(ctx context.Context, applyId string) error {
	groupApplyApplyIdKey := fmt.Sprintf("%s%v", cacheGroupApplyApplyIdPrefix, applyId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `apply_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, applyId)
	}, groupApplyApplyIdKey)
	return err
}

func (m *defaultGroupApplyModel) FindOne(ctx context.Context, applyId string) (*GroupApply, error) {
	groupApplyApplyIdKey := fmt.Sprintf("%s%v", cacheGroupApplyApplyIdPrefix, applyId)
	var resp GroupApply
	err := m.QueryRowCtx(ctx, &resp, groupApplyApplyIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `apply_id` = ? limit 1", groupApplyRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, applyId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultGroupApplyModel) InsertByTargetIdList(ctx context.Context,session sqlx.Session,data ...*GroupApply) (sql.Result, error) {
	var (
		sql strings.Builder
		args []any
	)
	if len(data) == 0 {
		return nil, nil
	}
	sql.WriteString(fmt.Sprintf("insert into %s (%s) values ",m.table,groupApplyRowsExpectAutoSet))
	for i,v := range data {
		sql.WriteString("(?, ?, ?, ?, ?)")
		args = append(args,v.ApplyId, v.ApplicantId, v.TargetId, v.GreetMsg, v.Status)
		if i == len(data) - 1 {
			break
		}
		sql.WriteString(",")
	}
	return session.ExecCtx(ctx,sql.String(),args...)
}
func (m *defaultGroupApplyModel) Insert(ctx context.Context, data *GroupApply) (sql.Result, error) {
	groupApplyApplyIdKey := fmt.Sprintf("%s%v", cacheGroupApplyApplyIdPrefix, data.ApplyId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, groupApplyRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ApplyId, data.ApplicantId, data.TargetId, data.GreetMsg, data.Status)
	}, groupApplyApplyIdKey)
	return ret, err
}

func (m *defaultGroupApplyModel) Update(ctx context.Context,session sqlx.Session, data *GroupApply) error {
	groupApplyApplyIdKey := fmt.Sprintf("%s%v", cacheGroupApplyApplyIdPrefix, data.ApplyId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `apply_id` = ?", m.table, groupApplyRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.ApplicantId, data.TargetId, data.GreetMsg, data.Status, data.ApplyId)
	}, groupApplyApplyIdKey)
	return err
}

func (m *defaultGroupApplyModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGroupApplyApplyIdPrefix, primary)
}

func (m *defaultGroupApplyModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `apply_id` = ? limit 1", groupApplyRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultGroupApplyModel) tableName() string {
	return m.table
}
