// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: apps/dynamics/rpc/dynamics.proto

package dynamics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ================== 枚举定义 ==================
// 动态内容类型（文字/图文）[7](@ref)
type ContentType int32

const (
	ContentType_TEXT             ContentType = 0 // 纯文字动态
	ContentType_TEXT_WITH_IMAGES ContentType = 1 // 图文混合动态（静态图）
	ContentType_TEXT_WITH_GIF    ContentType = 2 // 图文混合动态（支持动态图）
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "TEXT",
		1: "TEXT_WITH_IMAGES",
		2: "TEXT_WITH_GIF",
	}
	ContentType_value = map[string]int32{
		"TEXT":             0,
		"TEXT_WITH_IMAGES": 1,
		"TEXT_WITH_GIF":    2,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_dynamics_rpc_dynamics_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_apps_dynamics_rpc_dynamics_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{0}
}

// 动态可见范围控制[6](@ref)
type VisibleScope int32

const (
	VisibleScope_FRIENDS VisibleScope = 0 // 仅好友可见
	VisibleScope_PRIVATE VisibleScope = 1 // 仅自己可见
	VisibleScope_CUSTOM  VisibleScope = 2 // 自定义用户可见
)

// Enum value maps for VisibleScope.
var (
	VisibleScope_name = map[int32]string{
		0: "FRIENDS",
		1: "PRIVATE",
		2: "CUSTOM",
	}
	VisibleScope_value = map[string]int32{
		"FRIENDS": 0,
		"PRIVATE": 1,
		"CUSTOM":  2,
	}
)

func (x VisibleScope) Enum() *VisibleScope {
	p := new(VisibleScope)
	*p = x
	return p
}

func (x VisibleScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VisibleScope) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_dynamics_rpc_dynamics_proto_enumTypes[1].Descriptor()
}

func (VisibleScope) Type() protoreflect.EnumType {
	return &file_apps_dynamics_rpc_dynamics_proto_enumTypes[1]
}

func (x VisibleScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VisibleScope.Descriptor instead.
func (VisibleScope) EnumDescriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{1}
}

// 通知事件类型[3](@ref)
type NotificationType int32

const (
	NotificationType_LIKE  NotificationType = 0 // 点赞通知
	NotificationType_REPLY NotificationType = 1 // 评论回复通知
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "LIKE",
		1: "REPLY",
	}
	NotificationType_value = map[string]int32{
		"LIKE":  0,
		"REPLY": 1,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_dynamics_rpc_dynamics_proto_enumTypes[2].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_apps_dynamics_rpc_dynamics_proto_enumTypes[2]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{2}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{0}
}

// ================== 消息结构 ==================
// 动态内容主体（支持文字/图片/GIF/表情）[7](@ref)
type PostContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                            // 文字内容（必填）
	ImageUrls     []string               `protobuf:"bytes,2,rep,name=image_urls,json=imageUrls,proto3" json:"image_urls,omitempty"` // 图片或GIF的URL列表（最多9个）[4](@ref)
	Emoji         string                 `protobuf:"bytes,3,opt,name=emoji,proto3" json:"emoji,omitempty"`                          // 表情符号（Unicode或自定义标识）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostContent) Reset() {
	*x = PostContent{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostContent) ProtoMessage() {}

func (x *PostContent) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostContent.ProtoReflect.Descriptor instead.
func (*PostContent) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{1}
}

func (x *PostContent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *PostContent) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *PostContent) GetEmoji() string {
	if x != nil {
		return x.Emoji
	}
	return ""
}

// 动态元数据（隐私控制与附加信息）
type PostMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Location       string                 `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`                                     // 发布地点（如"北京·故宫"）
	Scope          VisibleScope           `protobuf:"varint,2,opt,name=scope,proto3,enum=dynamics.VisibleScope" json:"scope,omitempty"`               // 可见范围控制[6](@ref)
	VisibleUserIds []string               `protobuf:"bytes,3,rep,name=visible_user_ids,json=visibleUserIds,proto3" json:"visible_user_ids,omitempty"` // 当scope=CUSTOM时生效的可见用户ID列表
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostMeta) Reset() {
	*x = PostMeta{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMeta) ProtoMessage() {}

func (x *PostMeta) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMeta.ProtoReflect.Descriptor instead.
func (*PostMeta) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{2}
}

func (x *PostMeta) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *PostMeta) GetScope() VisibleScope {
	if x != nil {
		return x.Scope
	}
	return VisibleScope_FRIENDS
}

func (x *PostMeta) GetVisibleUserIds() []string {
	if x != nil {
		return x.VisibleUserIds
	}
	return nil
}

// 动态核心结构
type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`        // 动态唯一ID（服务端生成）
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`        // 发布者ID
	Content       *PostContent           `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`                    // 动态内容主体
	Meta          *PostMeta              `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`                          // 动态元数据
	IsPinned      bool                   `protobuf:"varint,5,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"` // 是否置顶（置顶动态不参与时间线排序）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{3}
}

func (x *Post) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Post) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Post) GetContent() *PostContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Post) GetMeta() *PostMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Post) GetIsPinned() bool {
	if x != nil {
		return x.IsPinned
	}
	return false
}

// 点赞/取消点赞操作
type LikeAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`        // 目标动态ID
	LikerId       string                 `protobuf:"bytes,2,opt,name=liker_id,json=likerId,proto3" json:"liker_id,omitempty"`     // 操作者ID
	IsCancel      bool                   `protobuf:"varint,3,opt,name=is_cancel,json=isCancel,proto3" json:"is_cancel,omitempty"` // true=取消点赞，false=点赞
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeAction) Reset() {
	*x = LikeAction{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeAction) ProtoMessage() {}

func (x *LikeAction) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeAction.ProtoReflect.Descriptor instead.
func (*LikeAction) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{4}
}

func (x *LikeAction) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *LikeAction) GetLikerId() string {
	if x != nil {
		return x.LikerId
	}
	return ""
}

func (x *LikeAction) GetIsCancel() bool {
	if x != nil {
		return x.IsCancel
	}
	return false
}

// 通知信息（支持点赞/评论回复）
type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                              // 通知唯一ID
	Type          NotificationType       `protobuf:"varint,2,opt,name=type,proto3,enum=dynamics.NotificationType" json:"type,omitempty"`          // 通知类型[3](@ref)
	TriggerUserId string                 `protobuf:"bytes,3,opt,name=trigger_user_id,json=triggerUserId,proto3" json:"trigger_user_id,omitempty"` // 触发通知的用户ID
	PostId        string                 `protobuf:"bytes,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`                        // 关联的动态ID
	CommentId     string                 `protobuf:"bytes,5,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`               // 关联的评论ID（仅REPLY类型有效）
	IsRead        bool                   `protobuf:"varint,6,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`                       // 是否已读（新增字段）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{5}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_LIKE
}

func (x *Notification) GetTriggerUserId() string {
	if x != nil {
		return x.TriggerUserId
	}
	return ""
}

func (x *Notification) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *Notification) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

// 分页请求结构[1](@ref)
type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`   // 每页数量（建议值：10-20）
	PageToken     string                 `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"` // 翻页令牌（首次请求留空，后续使用响应中的next_page_token）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{6}
}

func (x *Pagination) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// 动态列表响应
type PostListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`                                        // 动态列表
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 下一页令牌（无更多数据时为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostListResponse) Reset() {
	*x = PostListResponse{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostListResponse) ProtoMessage() {}

func (x *PostListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostListResponse.ProtoReflect.Descriptor instead.
func (*PostListResponse) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{7}
}

func (x *PostListResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *PostListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// ================== 请求/响应结构 ==================
type CreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 发布者ID
	Content       *PostContent           `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`             // 动态内容
	Meta          *PostMeta              `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`                   // 动态元数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostRequest) Reset() {
	*x = CreatePostRequest{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostRequest) ProtoMessage() {}

func (x *CreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostRequest.ProtoReflect.Descriptor instead.
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{8}
}

func (x *CreatePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePostRequest) GetContent() *PostContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *CreatePostRequest) GetMeta() *PostMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeletePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 操作者ID（需与动态创建者匹配）
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"` // 要删除的动态ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePostRequest) Reset() {
	*x = DeletePostRequest{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePostRequest) ProtoMessage() {}

func (x *DeletePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePostRequest.ProtoReflect.Descriptor instead.
func (*DeletePostRequest) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeletePostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type PinPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 操作者ID（需与动态创建者匹配）
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"` // 目标动态ID
	Pin           bool                   `protobuf:"varint,3,opt,name=pin,proto3" json:"pin,omitempty"`                    // 操作标识（true=置顶，false=取消置顶）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PinPostRequest) Reset() {
	*x = PinPostRequest{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PinPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PinPostRequest) ProtoMessage() {}

func (x *PinPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PinPostRequest.ProtoReflect.Descriptor instead.
func (*PinPostRequest) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{10}
}

func (x *PinPostRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PinPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *PinPostRequest) GetPin() bool {
	if x != nil {
		return x.Pin
	}
	return false
}

type ListUserPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 目标用户ID
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`       // 分页参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserPostsRequest) Reset() {
	*x = ListUserPostsRequest{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserPostsRequest) ProtoMessage() {}

func (x *ListUserPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserPostsRequest.ProtoReflect.Descriptor instead.
func (*ListUserPostsRequest) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{11}
}

func (x *ListUserPostsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserPostsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SetCoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 用户ID
	CoverUrl      string                 `protobuf:"bytes,2,opt,name=cover_url,json=coverUrl,proto3" json:"cover_url,omitempty"` // 封面图URL（需CDN地址）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetCoverRequest) Reset() {
	*x = SetCoverRequest{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetCoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCoverRequest) ProtoMessage() {}

func (x *SetCoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCoverRequest.ProtoReflect.Descriptor instead.
func (*SetCoverRequest) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{12}
}

func (x *SetCoverRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetCoverRequest) GetCoverUrl() string {
	if x != nil {
		return x.CoverUrl
	}
	return ""
}

type ListVisiblePostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ViewerId      string                 `protobuf:"bytes,1,opt,name=viewer_id,json=viewerId,proto3" json:"viewer_id,omitempty"` // 浏览者ID（用于权限校验）
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`             // 分页参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVisiblePostsRequest) Reset() {
	*x = ListVisiblePostsRequest{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVisiblePostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVisiblePostsRequest) ProtoMessage() {}

func (x *ListVisiblePostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVisiblePostsRequest.ProtoReflect.Descriptor instead.
func (*ListVisiblePostsRequest) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{13}
}

func (x *ListVisiblePostsRequest) GetViewerId() string {
	if x != nil {
		return x.ViewerId
	}
	return ""
}

func (x *ListVisiblePostsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`       // 分页参数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{14}
}

func (x *ListNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListNotificationsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`                        // 通知列表
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"` // 下一页令牌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{15}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// 新增：未读通知计数请求
type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{16}
}

func (x *GetUnreadCountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// 新增：未读通知计数响应
type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount   int32                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"` // 未读通知总数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_dynamics_rpc_dynamics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP(), []int{17}
}

func (x *GetUnreadCountResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

var File_apps_dynamics_rpc_dynamics_proto protoreflect.FileDescriptor

const file_apps_dynamics_rpc_dynamics_proto_rawDesc = "" +
	"\n" +
	" apps/dynamics/rpc/dynamics.proto\x12\bdynamics\"\a\n" +
	"\x05Empty\"V\n" +
	"\vPostContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"image_urls\x18\x02 \x03(\tR\timageUrls\x12\x14\n" +
	"\x05emoji\x18\x03 \x01(\tR\x05emoji\"~\n" +
	"\bPostMeta\x12\x1a\n" +
	"\blocation\x18\x01 \x01(\tR\blocation\x12,\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x16.dynamics.VisibleScopeR\x05scope\x12(\n" +
	"\x10visible_user_ids\x18\x03 \x03(\tR\x0evisibleUserIds\"\xae\x01\n" +
	"\x04Post\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12/\n" +
	"\acontent\x18\x03 \x01(\v2\x15.dynamics.PostContentR\acontent\x12&\n" +
	"\x04meta\x18\x04 \x01(\v2\x12.dynamics.PostMetaR\x04meta\x12\x1b\n" +
	"\tis_pinned\x18\x05 \x01(\bR\bisPinned\"]\n" +
	"\n" +
	"LikeAction\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\x12\x19\n" +
	"\bliker_id\x18\x02 \x01(\tR\alikerId\x12\x1b\n" +
	"\tis_cancel\x18\x03 \x01(\bR\bisCancel\"\xc7\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.dynamics.NotificationTypeR\x04type\x12&\n" +
	"\x0ftrigger_user_id\x18\x03 \x01(\tR\rtriggerUserId\x12\x17\n" +
	"\apost_id\x18\x04 \x01(\tR\x06postId\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x05 \x01(\tR\tcommentId\x12\x17\n" +
	"\ais_read\x18\x06 \x01(\bR\x06isRead\"H\n" +
	"\n" +
	"Pagination\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\"`\n" +
	"\x10PostListResponse\x12$\n" +
	"\x05posts\x18\x01 \x03(\v2\x0e.dynamics.PostR\x05posts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x85\x01\n" +
	"\x11CreatePostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12/\n" +
	"\acontent\x18\x02 \x01(\v2\x15.dynamics.PostContentR\acontent\x12&\n" +
	"\x04meta\x18\x03 \x01(\v2\x12.dynamics.PostMetaR\x04meta\"E\n" +
	"\x11DeletePostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"T\n" +
	"\x0ePinPostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\x12\x10\n" +
	"\x03pin\x18\x03 \x01(\bR\x03pin\"e\n" +
	"\x14ListUserPostsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.dynamics.PaginationR\n" +
	"pagination\"G\n" +
	"\x0fSetCoverRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tcover_url\x18\x02 \x01(\tR\bcoverUrl\"l\n" +
	"\x17ListVisiblePostsRequest\x12\x1b\n" +
	"\tviewer_id\x18\x01 \x01(\tR\bviewerId\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.dynamics.PaginationR\n" +
	"pagination\"i\n" +
	"\x18ListNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x124\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x14.dynamics.PaginationR\n" +
	"pagination\"\x81\x01\n" +
	"\x19ListNotificationsResponse\x12<\n" +
	"\rnotifications\x18\x01 \x03(\v2\x16.dynamics.NotificationR\rnotifications\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"0\n" +
	"\x15GetUnreadCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\";\n" +
	"\x16GetUnreadCountResponse\x12!\n" +
	"\funread_count\x18\x01 \x01(\x05R\vunreadCount*@\n" +
	"\vContentType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\x14\n" +
	"\x10TEXT_WITH_IMAGES\x10\x01\x12\x11\n" +
	"\rTEXT_WITH_GIF\x10\x02*4\n" +
	"\fVisibleScope\x12\v\n" +
	"\aFRIENDS\x10\x00\x12\v\n" +
	"\aPRIVATE\x10\x01\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x02*'\n" +
	"\x10NotificationType\x12\b\n" +
	"\x04LIKE\x10\x00\x12\t\n" +
	"\x05REPLY\x10\x012\xf7\x04\n" +
	"\bdynamics\x129\n" +
	"\n" +
	"CreatePost\x12\x1b.dynamics.CreatePostRequest\x1a\x0e.dynamics.Post\x12:\n" +
	"\n" +
	"DeletePost\x12\x1b.dynamics.DeletePostRequest\x1a\x0f.dynamics.Empty\x123\n" +
	"\n" +
	"ToggleLike\x12\x14.dynamics.LikeAction\x1a\x0f.dynamics.Empty\x124\n" +
	"\aPinPost\x12\x18.dynamics.PinPostRequest\x1a\x0f.dynamics.Empty\x12K\n" +
	"\rListUserPosts\x12\x1e.dynamics.ListUserPostsRequest\x1a\x1a.dynamics.PostListResponse\x126\n" +
	"\bSetCover\x12\x19.dynamics.SetCoverRequest\x1a\x0f.dynamics.Empty\x12Q\n" +
	"\x10ListVisiblePosts\x12!.dynamics.ListVisiblePostsRequest\x1a\x1a.dynamics.PostListResponse\x12\\\n" +
	"\x11ListNotifications\x12\".dynamics.ListNotificationsRequest\x1a#.dynamics.ListNotificationsResponse\x12S\n" +
	"\x0eGetUnreadCount\x12\x1f.dynamics.GetUnreadCountRequest\x1a .dynamics.GetUnreadCountResponseB\fZ\n" +
	"./dynamicsb\x06proto3"

var (
	file_apps_dynamics_rpc_dynamics_proto_rawDescOnce sync.Once
	file_apps_dynamics_rpc_dynamics_proto_rawDescData []byte
)

func file_apps_dynamics_rpc_dynamics_proto_rawDescGZIP() []byte {
	file_apps_dynamics_rpc_dynamics_proto_rawDescOnce.Do(func() {
		file_apps_dynamics_rpc_dynamics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_dynamics_rpc_dynamics_proto_rawDesc), len(file_apps_dynamics_rpc_dynamics_proto_rawDesc)))
	})
	return file_apps_dynamics_rpc_dynamics_proto_rawDescData
}

var file_apps_dynamics_rpc_dynamics_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_apps_dynamics_rpc_dynamics_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_apps_dynamics_rpc_dynamics_proto_goTypes = []any{
	(ContentType)(0),                  // 0: dynamics.ContentType
	(VisibleScope)(0),                 // 1: dynamics.VisibleScope
	(NotificationType)(0),             // 2: dynamics.NotificationType
	(*Empty)(nil),                     // 3: dynamics.Empty
	(*PostContent)(nil),               // 4: dynamics.PostContent
	(*PostMeta)(nil),                  // 5: dynamics.PostMeta
	(*Post)(nil),                      // 6: dynamics.Post
	(*LikeAction)(nil),                // 7: dynamics.LikeAction
	(*Notification)(nil),              // 8: dynamics.Notification
	(*Pagination)(nil),                // 9: dynamics.Pagination
	(*PostListResponse)(nil),          // 10: dynamics.PostListResponse
	(*CreatePostRequest)(nil),         // 11: dynamics.CreatePostRequest
	(*DeletePostRequest)(nil),         // 12: dynamics.DeletePostRequest
	(*PinPostRequest)(nil),            // 13: dynamics.PinPostRequest
	(*ListUserPostsRequest)(nil),      // 14: dynamics.ListUserPostsRequest
	(*SetCoverRequest)(nil),           // 15: dynamics.SetCoverRequest
	(*ListVisiblePostsRequest)(nil),   // 16: dynamics.ListVisiblePostsRequest
	(*ListNotificationsRequest)(nil),  // 17: dynamics.ListNotificationsRequest
	(*ListNotificationsResponse)(nil), // 18: dynamics.ListNotificationsResponse
	(*GetUnreadCountRequest)(nil),     // 19: dynamics.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),    // 20: dynamics.GetUnreadCountResponse
}
var file_apps_dynamics_rpc_dynamics_proto_depIdxs = []int32{
	1,  // 0: dynamics.PostMeta.scope:type_name -> dynamics.VisibleScope
	4,  // 1: dynamics.Post.content:type_name -> dynamics.PostContent
	5,  // 2: dynamics.Post.meta:type_name -> dynamics.PostMeta
	2,  // 3: dynamics.Notification.type:type_name -> dynamics.NotificationType
	6,  // 4: dynamics.PostListResponse.posts:type_name -> dynamics.Post
	4,  // 5: dynamics.CreatePostRequest.content:type_name -> dynamics.PostContent
	5,  // 6: dynamics.CreatePostRequest.meta:type_name -> dynamics.PostMeta
	9,  // 7: dynamics.ListUserPostsRequest.pagination:type_name -> dynamics.Pagination
	9,  // 8: dynamics.ListVisiblePostsRequest.pagination:type_name -> dynamics.Pagination
	9,  // 9: dynamics.ListNotificationsRequest.pagination:type_name -> dynamics.Pagination
	8,  // 10: dynamics.ListNotificationsResponse.notifications:type_name -> dynamics.Notification
	11, // 11: dynamics.dynamics.CreatePost:input_type -> dynamics.CreatePostRequest
	12, // 12: dynamics.dynamics.DeletePost:input_type -> dynamics.DeletePostRequest
	7,  // 13: dynamics.dynamics.ToggleLike:input_type -> dynamics.LikeAction
	13, // 14: dynamics.dynamics.PinPost:input_type -> dynamics.PinPostRequest
	14, // 15: dynamics.dynamics.ListUserPosts:input_type -> dynamics.ListUserPostsRequest
	15, // 16: dynamics.dynamics.SetCover:input_type -> dynamics.SetCoverRequest
	16, // 17: dynamics.dynamics.ListVisiblePosts:input_type -> dynamics.ListVisiblePostsRequest
	17, // 18: dynamics.dynamics.ListNotifications:input_type -> dynamics.ListNotificationsRequest
	19, // 19: dynamics.dynamics.GetUnreadCount:input_type -> dynamics.GetUnreadCountRequest
	6,  // 20: dynamics.dynamics.CreatePost:output_type -> dynamics.Post
	3,  // 21: dynamics.dynamics.DeletePost:output_type -> dynamics.Empty
	3,  // 22: dynamics.dynamics.ToggleLike:output_type -> dynamics.Empty
	3,  // 23: dynamics.dynamics.PinPost:output_type -> dynamics.Empty
	10, // 24: dynamics.dynamics.ListUserPosts:output_type -> dynamics.PostListResponse
	3,  // 25: dynamics.dynamics.SetCover:output_type -> dynamics.Empty
	10, // 26: dynamics.dynamics.ListVisiblePosts:output_type -> dynamics.PostListResponse
	18, // 27: dynamics.dynamics.ListNotifications:output_type -> dynamics.ListNotificationsResponse
	20, // 28: dynamics.dynamics.GetUnreadCount:output_type -> dynamics.GetUnreadCountResponse
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_apps_dynamics_rpc_dynamics_proto_init() }
func file_apps_dynamics_rpc_dynamics_proto_init() {
	if File_apps_dynamics_rpc_dynamics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_dynamics_rpc_dynamics_proto_rawDesc), len(file_apps_dynamics_rpc_dynamics_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_dynamics_rpc_dynamics_proto_goTypes,
		DependencyIndexes: file_apps_dynamics_rpc_dynamics_proto_depIdxs,
		EnumInfos:         file_apps_dynamics_rpc_dynamics_proto_enumTypes,
		MessageInfos:      file_apps_dynamics_rpc_dynamics_proto_msgTypes,
	}.Build()
	File_apps_dynamics_rpc_dynamics_proto = out.File
	file_apps_dynamics_rpc_dynamics_proto_goTypes = nil
	file_apps_dynamics_rpc_dynamics_proto_depIdxs = nil
}
