// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: apps/social/rpc/social.proto

package social

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 群操作权限类型
type GroupPermission int32

const (
	GroupPermission_KICK        GroupPermission = 0 // 踢出成员
	GroupPermission_SET_ADMIN   GroupPermission = 1 // 设置/取消管理员
	GroupPermission_CHANGE_NAME GroupPermission = 2 // 修改群名
)

// Enum value maps for GroupPermission.
var (
	GroupPermission_name = map[int32]string{
		0: "KICK",
		1: "SET_ADMIN",
		2: "CHANGE_NAME",
	}
	GroupPermission_value = map[string]int32{
		"KICK":        0,
		"SET_ADMIN":   1,
		"CHANGE_NAME": 2,
	}
)

func (x GroupPermission) Enum() *GroupPermission {
	p := new(GroupPermission)
	*p = x
	return p
}

func (x GroupPermission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupPermission) Descriptor() protoreflect.EnumDescriptor {
	return file_apps_social_rpc_social_proto_enumTypes[0].Descriptor()
}

func (GroupPermission) Type() protoreflect.EnumType {
	return &file_apps_social_rpc_social_proto_enumTypes[0]
}

func (x GroupPermission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupPermission.Descriptor instead.
func (GroupPermission) EnumDescriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{0}
}

// ========== 基础数据结构 ==========
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户全局ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像URL
	Gender        uint32                 `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                       // 性别 (0-未知 1-男 2-女)
	Status        *FriendStatusInfo      `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                        //对于好友的状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserInfo) GetStatus() *FriendStatusInfo {
	if x != nil {
		return x.Status
	}
	return nil
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`           // 群ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                // 群名称
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`           // 群主ID
	AdminIds      []string               `protobuf:"bytes,4,rep,name=admin_ids,json=adminIds,proto3" json:"admin_ids,omitempty"`        // 管理员ID列表
	MemberIds     []string               `protobuf:"bytes,5,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"`     // 成员ID列表
	MaxMembers    uint32                 `protobuf:"varint,6,opt,name=max_members,json=maxMembers,proto3" json:"max_members,omitempty"` // 群人数上限
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{1}
}

func (x *GroupInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GroupInfo) GetAdminIds() []string {
	if x != nil {
		return x.AdminIds
	}
	return nil
}

func (x *GroupInfo) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

func (x *GroupInfo) GetMaxMembers() uint32 {
	if x != nil {
		return x.MaxMembers
	}
	return 0
}

// ========== 好友管理模块 ==========
type FriendStatusInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMuted       bool                   `protobuf:"varint,1,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`       // 消息免打扰
	IsTopped      bool                   `protobuf:"varint,2,opt,name=is_topped,json=isTopped,proto3" json:"is_topped,omitempty"`    // 置顶聊天
	IsBlocked     bool                   `protobuf:"varint,3,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"` // 拉黑好友
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`                         // 好友备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendStatusInfo) Reset() {
	*x = FriendStatusInfo{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendStatusInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendStatusInfo) ProtoMessage() {}

func (x *FriendStatusInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendStatusInfo.ProtoReflect.Descriptor instead.
func (*FriendStatusInfo) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{2}
}

func (x *FriendStatusInfo) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

func (x *FriendStatusInfo) GetIsTopped() bool {
	if x != nil {
		return x.IsTopped
	}
	return false
}

func (x *FriendStatusInfo) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *FriendStatusInfo) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 好友状态设置 (免打扰/置顶/黑名单)
type FriendStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMuted       *bool                  `protobuf:"varint,1,opt,name=is_muted,json=isMuted,proto3,oneof" json:"is_muted,omitempty"`       // 消息免打扰
	IsTopped      *bool                  `protobuf:"varint,2,opt,name=is_topped,json=isTopped,proto3,oneof" json:"is_topped,omitempty"`    // 置顶聊天
	IsBlocked     *bool                  `protobuf:"varint,3,opt,name=is_blocked,json=isBlocked,proto3,oneof" json:"is_blocked,omitempty"` // 拉黑好友
	Remark        *string                `protobuf:"bytes,4,opt,name=remark,proto3,oneof" json:"remark,omitempty"`                         // 好友备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendStatus) Reset() {
	*x = FriendStatus{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendStatus) ProtoMessage() {}

func (x *FriendStatus) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendStatus.ProtoReflect.Descriptor instead.
func (*FriendStatus) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{3}
}

func (x *FriendStatus) GetIsMuted() bool {
	if x != nil && x.IsMuted != nil {
		return *x.IsMuted
	}
	return false
}

func (x *FriendStatus) GetIsTopped() bool {
	if x != nil && x.IsTopped != nil {
		return *x.IsTopped
	}
	return false
}

func (x *FriendStatus) GetIsBlocked() bool {
	if x != nil && x.IsBlocked != nil {
		return *x.IsBlocked
	}
	return false
}

func (x *FriendStatus) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

// 好友申请请求
type FriendApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicantId   string                 `protobuf:"bytes,1,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"` // 申请人ID
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`          // 目标用户ID
	GreetMsg      string                 `protobuf:"bytes,3,opt,name=greet_msg,json=greetMsg,proto3" json:"greet_msg,omitempty"`          // 打招呼消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplyRequest) Reset() {
	*x = FriendApplyRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplyRequest) ProtoMessage() {}

func (x *FriendApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplyRequest.ProtoReflect.Descriptor instead.
func (*FriendApplyRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{4}
}

func (x *FriendApplyRequest) GetApplicantId() string {
	if x != nil {
		return x.ApplicantId
	}
	return ""
}

func (x *FriendApplyRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *FriendApplyRequest) GetGreetMsg() string {
	if x != nil {
		return x.GreetMsg
	}
	return ""
}

// 好友申请响应
type FriendApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       string                 `protobuf:"bytes,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"` // 申请记录ID
	ApplyTime     int64                  `protobuf:"varint,2,opt,name=apply_time,json=applyTime,proto3" json:"apply_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplyResponse) Reset() {
	*x = FriendApplyResponse{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplyResponse) ProtoMessage() {}

func (x *FriendApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplyResponse.ProtoReflect.Descriptor instead.
func (*FriendApplyResponse) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{5}
}

func (x *FriendApplyResponse) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

func (x *FriendApplyResponse) GetApplyTime() int64 {
	if x != nil {
		return x.ApplyTime
	}
	return 0
}

type FriendApplyListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplyListReq) Reset() {
	*x = FriendApplyListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplyListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplyListReq) ProtoMessage() {}

func (x *FriendApplyListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplyListReq.ProtoReflect.Descriptor instead.
func (*FriendApplyListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{6}
}

func (x *FriendApplyListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FriendApplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户全局ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像URL
	Gender        uint32                 `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                       // 性别 (0-未知 1-男 2-女)
	GreetMsg      string                 `protobuf:"bytes,5,opt,name=greet_msg,json=greetMsg,proto3" json:"greet_msg,omitempty"`    // 打招呼消息
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                       //申请状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplyResp) Reset() {
	*x = FriendApplyResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplyResp) ProtoMessage() {}

func (x *FriendApplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplyResp.ProtoReflect.Descriptor instead.
func (*FriendApplyResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{7}
}

func (x *FriendApplyResp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendApplyResp) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *FriendApplyResp) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *FriendApplyResp) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *FriendApplyResp) GetGreetMsg() string {
	if x != nil {
		return x.GreetMsg
	}
	return ""
}

func (x *FriendApplyResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type FriendApplyListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*FriendApplyResp     `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplyListResp) Reset() {
	*x = FriendApplyListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplyListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplyListResp) ProtoMessage() {}

func (x *FriendApplyListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplyListResp.ProtoReflect.Descriptor instead.
func (*FriendApplyListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{8}
}

func (x *FriendApplyListResp) GetList() []*FriendApplyResp {
	if x != nil {
		return x.List
	}
	return nil
}

// 好友申请操作
type FriendApplyAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       string                 `protobuf:"bytes,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`           // 申请记录ID
	IsApproved    bool                   `protobuf:"varint,2,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"` // 是否同意
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplyAction) Reset() {
	*x = FriendApplyAction{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplyAction) ProtoMessage() {}

func (x *FriendApplyAction) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplyAction.ProtoReflect.Descriptor instead.
func (*FriendApplyAction) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{9}
}

func (x *FriendApplyAction) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

func (x *FriendApplyAction) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

// ========== 群组管理模块 ==========
// 群成员个性化设置
type GroupMemberSetting struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GroupNickname      *string                `protobuf:"bytes,1,opt,name=group_nickname,json=groupNickname,proto3,oneof" json:"group_nickname,omitempty"`                   // 群内昵称
	ShowMemberNickname *bool                  `protobuf:"varint,2,opt,name=show_member_nickname,json=showMemberNickname,proto3,oneof" json:"show_member_nickname,omitempty"` // 是否显示群成员昵称
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupMemberSetting) Reset() {
	*x = GroupMemberSetting{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberSetting) ProtoMessage() {}

func (x *GroupMemberSetting) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberSetting.ProtoReflect.Descriptor instead.
func (*GroupMemberSetting) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{10}
}

func (x *GroupMemberSetting) GetGroupNickname() string {
	if x != nil && x.GroupNickname != nil {
		return *x.GroupNickname
	}
	return ""
}

func (x *GroupMemberSetting) GetShowMemberNickname() bool {
	if x != nil && x.ShowMemberNickname != nil {
		return *x.ShowMemberNickname
	}
	return false
}

// 群状态设置
type GroupStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMuted       *bool                  `protobuf:"varint,1,opt,name=is_muted,json=isMuted,proto3,oneof" json:"is_muted,omitempty"`    // 群消息免打扰
	IsTopped      *bool                  `protobuf:"varint,2,opt,name=is_topped,json=isTopped,proto3,oneof" json:"is_topped,omitempty"` // 置顶群聊
	Remark        *string                `protobuf:"bytes,3,opt,name=remark,proto3,oneof" json:"remark,omitempty"`                      // 群备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupStatus) Reset() {
	*x = GroupStatus{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStatus) ProtoMessage() {}

func (x *GroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStatus.ProtoReflect.Descriptor instead.
func (*GroupStatus) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{11}
}

func (x *GroupStatus) GetIsMuted() bool {
	if x != nil && x.IsMuted != nil {
		return *x.IsMuted
	}
	return false
}

func (x *GroupStatus) GetIsTopped() bool {
	if x != nil && x.IsTopped != nil {
		return *x.IsTopped
	}
	return false
}

func (x *GroupStatus) GetRemark() string {
	if x != nil && x.Remark != nil {
		return *x.Remark
	}
	return ""
}

// 群邀请请求
type GroupInvitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviterId     string                 `protobuf:"bytes,1,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"` // 邀请人ID（群主/管理员）
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`       // 群ID
	TargetIds     []string               `protobuf:"bytes,3,rep,name=target_ids,json=targetIds,proto3" json:"target_ids,omitempty"` // 被邀请人ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInvitation) Reset() {
	*x = GroupInvitation{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInvitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInvitation) ProtoMessage() {}

func (x *GroupInvitation) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInvitation.ProtoReflect.Descriptor instead.
func (*GroupInvitation) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{12}
}

func (x *GroupInvitation) GetInviterId() string {
	if x != nil {
		return x.InviterId
	}
	return ""
}

func (x *GroupInvitation) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInvitation) GetTargetIds() []string {
	if x != nil {
		return x.TargetIds
	}
	return nil
}

type FriendApplyActionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsApproved    bool                   `protobuf:"varint,1,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"` //是否成功
	ApplicantId   string                 `protobuf:"bytes,2,opt,name=applicantId,proto3" json:"applicantId,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendApplyActionResp) Reset() {
	*x = FriendApplyActionResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendApplyActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendApplyActionResp) ProtoMessage() {}

func (x *FriendApplyActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendApplyActionResp.ProtoReflect.Descriptor instead.
func (*FriendApplyActionResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{13}
}

func (x *FriendApplyActionResp) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *FriendApplyActionResp) GetApplicantId() string {
	if x != nil {
		return x.ApplicantId
	}
	return ""
}

func (x *FriendApplyActionResp) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type RelationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationResp) Reset() {
	*x = RelationResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationResp) ProtoMessage() {}

func (x *RelationResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationResp.ProtoReflect.Descriptor instead.
func (*RelationResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{14}
}

type FriendStatusUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendStatusUpdateResp) Reset() {
	*x = FriendStatusUpdateResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendStatusUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendStatusUpdateResp) ProtoMessage() {}

func (x *FriendStatusUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendStatusUpdateResp.ProtoReflect.Descriptor instead.
func (*FriendStatusUpdateResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{15}
}

type GroupInviteActionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsApproved    bool                   `protobuf:"varint,1,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInviteActionResp) Reset() {
	*x = GroupInviteActionResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteActionResp) ProtoMessage() {}

func (x *GroupInviteActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInviteActionResp.ProtoReflect.Descriptor instead.
func (*GroupInviteActionResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{16}
}

func (x *GroupInviteActionResp) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *GroupInviteActionResp) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *GroupInviteActionResp) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type GroupStatusUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupStatusUpdateResp) Reset() {
	*x = GroupStatusUpdateResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStatusUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStatusUpdateResp) ProtoMessage() {}

func (x *GroupStatusUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStatusUpdateResp.ProtoReflect.Descriptor instead.
func (*GroupStatusUpdateResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{17}
}

type GroupMemberManageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberManageResp) Reset() {
	*x = GroupMemberManageResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberManageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberManageResp) ProtoMessage() {}

func (x *GroupMemberManageResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberManageResp.ProtoReflect.Descriptor instead.
func (*GroupMemberManageResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{18}
}

type GroupMemberSettingUpdateResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberSettingUpdateResp) Reset() {
	*x = GroupMemberSettingUpdateResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberSettingUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberSettingUpdateResp) ProtoMessage() {}

func (x *GroupMemberSettingUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberSettingUpdateResp.ProtoReflect.Descriptor instead.
func (*GroupMemberSettingUpdateResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{19}
}

type GroupQuitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupQuitResp) Reset() {
	*x = GroupQuitResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupQuitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupQuitResp) ProtoMessage() {}

func (x *GroupQuitResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupQuitResp.ProtoReflect.Descriptor instead.
func (*GroupQuitResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{20}
}

type GroupInvitationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInvitationResp) Reset() {
	*x = GroupInvitationResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInvitationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInvitationResp) ProtoMessage() {}

func (x *GroupInvitationResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInvitationResp.ProtoReflect.Descriptor instead.
func (*GroupInvitationResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{21}
}

type FriendListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListReq) Reset() {
	*x = FriendListReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListReq) ProtoMessage() {}

func (x *FriendListReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListReq.ProtoReflect.Descriptor instead.
func (*FriendListReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{22}
}

func (x *FriendListReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FriendListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendList    []*UserInfo            `protobuf:"bytes,1,rep,name=friend_list,json=friendList,proto3" json:"friend_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendListResp) Reset() {
	*x = FriendListResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListResp) ProtoMessage() {}

func (x *FriendListResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListResp.ProtoReflect.Descriptor instead.
func (*FriendListResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{23}
}

func (x *FriendListResp) GetFriendList() []*UserInfo {
	if x != nil {
		return x.FriendList
	}
	return nil
}

type GroupApplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicantId   string                 `protobuf:"bytes,1,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"` // 申请人ID
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`          // 目标用户ID
	GreetMsg      string                 `protobuf:"bytes,3,opt,name=greet_msg,json=greetMsg,proto3" json:"greet_msg,omitempty"`          // 打招呼消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupApplyReq) Reset() {
	*x = GroupApplyReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyReq) ProtoMessage() {}

func (x *GroupApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyReq.ProtoReflect.Descriptor instead.
func (*GroupApplyReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{24}
}

func (x *GroupApplyReq) GetApplicantId() string {
	if x != nil {
		return x.ApplicantId
	}
	return ""
}

func (x *GroupApplyReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GroupApplyReq) GetGreetMsg() string {
	if x != nil {
		return x.GreetMsg
	}
	return ""
}

// 群组申请响应
type GroupApplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       string                 `protobuf:"bytes,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"` // 申请记录ID
	ApplyTime     int64                  `protobuf:"varint,2,opt,name=apply_time,json=applyTime,proto3" json:"apply_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupApplyResp) Reset() {
	*x = GroupApplyResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupApplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyResp) ProtoMessage() {}

func (x *GroupApplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyResp.ProtoReflect.Descriptor instead.
func (*GroupApplyResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{25}
}

func (x *GroupApplyResp) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

func (x *GroupApplyResp) GetApplyTime() int64 {
	if x != nil {
		return x.ApplyTime
	}
	return 0
}

type GroupApplyAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplyId       string                 `protobuf:"bytes,1,opt,name=apply_id,json=applyId,proto3" json:"apply_id,omitempty"`           // 申请记录ID
	ManagerId     string                 `protobuf:"bytes,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`     //处理人id
	IsApproved    bool                   `protobuf:"varint,3,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"` // 是否同意
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupApplyAction) Reset() {
	*x = GroupApplyAction{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupApplyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyAction) ProtoMessage() {}

func (x *GroupApplyAction) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyAction.ProtoReflect.Descriptor instead.
func (*GroupApplyAction) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{26}
}

func (x *GroupApplyAction) GetApplyId() string {
	if x != nil {
		return x.ApplyId
	}
	return ""
}

func (x *GroupApplyAction) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *GroupApplyAction) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

type GroupApplyActionResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsApproved    bool                   `protobuf:"varint,1,opt,name=is_approved,json=isApproved,proto3" json:"is_approved,omitempty"`
	ApplicationId string                 `protobuf:"bytes,2,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=targetId,proto3" json:"targetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupApplyActionResp) Reset() {
	*x = GroupApplyActionResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupApplyActionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupApplyActionResp) ProtoMessage() {}

func (x *GroupApplyActionResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupApplyActionResp.ProtoReflect.Descriptor instead.
func (*GroupApplyActionResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{27}
}

func (x *GroupApplyActionResp) GetIsApproved() bool {
	if x != nil {
		return x.IsApproved
	}
	return false
}

func (x *GroupApplyActionResp) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *GroupApplyActionResp) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type GetGroupMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` //群组id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersReq) Reset() {
	*x = GetGroupMembersReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersReq) ProtoMessage() {}

func (x *GetGroupMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersReq.ProtoReflect.Descriptor instead.
func (*GetGroupMembersReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{28}
}

func (x *GetGroupMembersReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type BaseUserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // 用户全局ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像URL
	Gender        uint32                 `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                       // 性别 (0-未知 1-男 2-女)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseUserInfo) Reset() {
	*x = BaseUserInfo{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseUserInfo) ProtoMessage() {}

func (x *BaseUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseUserInfo.ProtoReflect.Descriptor instead.
func (*BaseUserInfo) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{29}
}

func (x *BaseUserInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BaseUserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BaseUserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *BaseUserInfo) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type GetGroupMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*BaseUserInfo        `protobuf:"bytes,1,rep,name=List,proto3" json:"List,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupMembersResp) Reset() {
	*x = GetGroupMembersResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupMembersResp) ProtoMessage() {}

func (x *GetGroupMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupMembersResp.ProtoReflect.Descriptor instead.
func (*GetGroupMembersResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{30}
}

func (x *GetGroupMembersResp) GetList() []*BaseUserInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type RemoveAdminReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者ID
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 被操作成员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAdminReq) Reset() {
	*x = RemoveAdminReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminReq) ProtoMessage() {}

func (x *RemoveAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminReq.ProtoReflect.Descriptor instead.
func (*RemoveAdminReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{31}
}

func (x *RemoveAdminReq) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *RemoveAdminReq) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *RemoveAdminReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type RemoveAdminResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAdminResp) Reset() {
	*x = RemoveAdminResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAdminResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminResp) ProtoMessage() {}

func (x *RemoveAdminResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminResp.ProtoReflect.Descriptor instead.
func (*RemoveAdminResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{32}
}

type HandleFriendApplyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=targetId,proto3" json:"targetId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendApplyReq) Reset() {
	*x = HandleFriendApplyReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendApplyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendApplyReq) ProtoMessage() {}

func (x *HandleFriendApplyReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendApplyReq.ProtoReflect.Descriptor instead.
func (*HandleFriendApplyReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{33}
}

func (x *HandleFriendApplyReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type HandleFriendApplyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendApplyResp) Reset() {
	*x = HandleFriendApplyResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendApplyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendApplyResp) ProtoMessage() {}

func (x *HandleFriendApplyResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendApplyResp.ProtoReflect.Descriptor instead.
func (*HandleFriendApplyResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{34}
}

// ========== 详细结构定义 ==========
// 好友状态更新请求
type FriendStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 操作者ID
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 好友ID
	Status        *FriendStatus          `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                     // 新状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendStatusUpdate) Reset() {
	*x = FriendStatusUpdate{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendStatusUpdate) ProtoMessage() {}

func (x *FriendStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendStatusUpdate.ProtoReflect.Descriptor instead.
func (*FriendStatusUpdate) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{35}
}

func (x *FriendStatusUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendStatusUpdate) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *FriendStatusUpdate) GetStatus() *FriendStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// 群创建请求
type GroupCreationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     string                 `protobuf:"bytes,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"` // 创建者ID
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"` // 初始群名
	MemberIds     []string               `protobuf:"bytes,3,rep,name=member_ids,json=memberIds,proto3" json:"member_ids,omitempty"` // 初始成员ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreationRequest) Reset() {
	*x = GroupCreationRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreationRequest) ProtoMessage() {}

func (x *GroupCreationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreationRequest.ProtoReflect.Descriptor instead.
func (*GroupCreationRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{36}
}

func (x *GroupCreationRequest) GetCreatorId() string {
	if x != nil {
		return x.CreatorId
	}
	return ""
}

func (x *GroupCreationRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupCreationRequest) GetMemberIds() []string {
	if x != nil {
		return x.MemberIds
	}
	return nil
}

// 群成员管理操作
type GroupMemberManage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperatorId    string                 `protobuf:"bytes,1,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"` // 操作者ID
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`          // 被操作成员ID
	Action        GroupPermission        `protobuf:"varint,4,opt,name=action,proto3,enum=social.GroupPermission" json:"action,omitempty"` //操作
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberManage) Reset() {
	*x = GroupMemberManage{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberManage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberManage) ProtoMessage() {}

func (x *GroupMemberManage) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberManage.ProtoReflect.Descriptor instead.
func (*GroupMemberManage) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{37}
}

func (x *GroupMemberManage) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

func (x *GroupMemberManage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMemberManage) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GroupMemberManage) GetAction() GroupPermission {
	if x != nil {
		return x.Action
	}
	return GroupPermission_KICK
}

// 群邀请处理
type GroupInviteAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteId      string                 `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`        // 邀请记录ID
	IsAccepted    bool                   `protobuf:"varint,2,opt,name=is_accepted,json=isAccepted,proto3" json:"is_accepted,omitempty"` // 是否接受
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInviteAction) Reset() {
	*x = GroupInviteAction{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInviteAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInviteAction) ProtoMessage() {}

func (x *GroupInviteAction) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInviteAction.ProtoReflect.Descriptor instead.
func (*GroupInviteAction) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{38}
}

func (x *GroupInviteAction) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *GroupInviteAction) GetIsAccepted() bool {
	if x != nil {
		return x.IsAccepted
	}
	return false
}

// 群状态更新
type GroupStatusUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 操作者ID
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Status        *GroupStatus           `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // 新状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupStatusUpdate) Reset() {
	*x = GroupStatusUpdate{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStatusUpdate) ProtoMessage() {}

func (x *GroupStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStatusUpdate.ProtoReflect.Descriptor instead.
func (*GroupStatusUpdate) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{39}
}

func (x *GroupStatusUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupStatusUpdate) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupStatusUpdate) GetStatus() *GroupStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// 群成员设置更新
type GroupMemberSettingUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Setting       *GroupMemberSetting    `protobuf:"bytes,3,opt,name=setting,proto3" json:"setting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberSettingUpdate) Reset() {
	*x = GroupMemberSettingUpdate{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberSettingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberSettingUpdate) ProtoMessage() {}

func (x *GroupMemberSettingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberSettingUpdate.ProtoReflect.Descriptor instead.
func (*GroupMemberSettingUpdate) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{40}
}

func (x *GroupMemberSettingUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupMemberSettingUpdate) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupMemberSettingUpdate) GetSetting() *GroupMemberSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

// 关系操作通用请求
type RelationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromUid       string                 `protobuf:"bytes,1,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"` // 发起方
	ToUid         string                 `protobuf:"bytes,2,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`       // 目标方
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelationRequest) Reset() {
	*x = RelationRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelationRequest) ProtoMessage() {}

func (x *RelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelationRequest.ProtoReflect.Descriptor instead.
func (*RelationRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{41}
}

func (x *RelationRequest) GetFromUid() string {
	if x != nil {
		return x.FromUid
	}
	return ""
}

func (x *RelationRequest) GetToUid() string {
	if x != nil {
		return x.ToUid
	}
	return ""
}

// 群退出请求
type GroupQuitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 退出者ID
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupQuitRequest) Reset() {
	*x = GroupQuitRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupQuitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupQuitRequest) ProtoMessage() {}

func (x *GroupQuitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupQuitRequest.ProtoReflect.Descriptor instead.
func (*GroupQuitRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{42}
}

func (x *GroupQuitRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupQuitRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// 信息查询请求
type FriendInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 查询者ID
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` // 目标好友ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendInfoRequest) Reset() {
	*x = FriendInfoRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfoRequest) ProtoMessage() {}

func (x *FriendInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfoRequest.ProtoReflect.Descriptor instead.
func (*FriendInfoRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{43}
}

func (x *FriendInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FriendInfoRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type GroupInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`    // 查询者ID
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 目标群ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfoRequest) Reset() {
	*x = GroupInfoRequest{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfoRequest) ProtoMessage() {}

func (x *GroupInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfoRequest.ProtoReflect.Descriptor instead.
func (*GroupInfoRequest) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{44}
}

func (x *GroupInfoRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupInfoRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type PingReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReq) Reset() {
	*x = PingReq{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReq) ProtoMessage() {}

func (x *PingReq) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReq.ProtoReflect.Descriptor instead.
func (*PingReq) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{45}
}

type PingResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResp) Reset() {
	*x = PingResp{}
	mi := &file_apps_social_rpc_social_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResp) ProtoMessage() {}

func (x *PingResp) ProtoReflect() protoreflect.Message {
	mi := &file_apps_social_rpc_social_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResp.ProtoReflect.Descriptor instead.
func (*PingResp) Descriptor() ([]byte, []int) {
	return file_apps_social_rpc_social_proto_rawDescGZIP(), []int{46}
}

func (x *PingResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_apps_social_rpc_social_proto protoreflect.FileDescriptor

const file_apps_social_rpc_social_proto_rawDesc = "" +
	"\n" +
	"\x1capps/social/rpc/social.proto\x12\x06social\"\xa8\x01\n" +
	"\bUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\rR\x06gender\x120\n" +
	"\x06status\x18\x05 \x01(\v2\x18.social.FriendStatusInfoR\x06status\"\xb2\x01\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x1b\n" +
	"\tadmin_ids\x18\x04 \x03(\tR\badminIds\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x05 \x03(\tR\tmemberIds\x12\x1f\n" +
	"\vmax_members\x18\x06 \x01(\rR\n" +
	"maxMembers\"\x81\x01\n" +
	"\x10FriendStatusInfo\x12\x19\n" +
	"\bis_muted\x18\x01 \x01(\bR\aisMuted\x12\x1b\n" +
	"\tis_topped\x18\x02 \x01(\bR\bisTopped\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x03 \x01(\bR\tisBlocked\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"\xc6\x01\n" +
	"\fFriendStatus\x12\x1e\n" +
	"\bis_muted\x18\x01 \x01(\bH\x00R\aisMuted\x88\x01\x01\x12 \n" +
	"\tis_topped\x18\x02 \x01(\bH\x01R\bisTopped\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_blocked\x18\x03 \x01(\bH\x02R\tisBlocked\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\x04 \x01(\tH\x03R\x06remark\x88\x01\x01B\v\n" +
	"\t_is_mutedB\f\n" +
	"\n" +
	"_is_toppedB\r\n" +
	"\v_is_blockedB\t\n" +
	"\a_remark\"q\n" +
	"\x12FriendApplyRequest\x12!\n" +
	"\fapplicant_id\x18\x01 \x01(\tR\vapplicantId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1b\n" +
	"\tgreet_msg\x18\x03 \x01(\tR\bgreetMsg\"O\n" +
	"\x13FriendApplyResponse\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\tR\aapplyId\x12\x1d\n" +
	"\n" +
	"apply_time\x18\x02 \x01(\x03R\tapplyTime\"-\n" +
	"\x12FriendApplyListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xb2\x01\n" +
	"\x0fFriendApplyResp\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\rR\x06gender\x12\x1b\n" +
	"\tgreet_msg\x18\x05 \x01(\tR\bgreetMsg\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\"B\n" +
	"\x13FriendApplyListResp\x12+\n" +
	"\x04List\x18\x01 \x03(\v2\x17.social.FriendApplyRespR\x04List\"O\n" +
	"\x11FriendApplyAction\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\tR\aapplyId\x12\x1f\n" +
	"\vis_approved\x18\x02 \x01(\bR\n" +
	"isApproved\"\xa3\x01\n" +
	"\x12GroupMemberSetting\x12*\n" +
	"\x0egroup_nickname\x18\x01 \x01(\tH\x00R\rgroupNickname\x88\x01\x01\x125\n" +
	"\x14show_member_nickname\x18\x02 \x01(\bH\x01R\x12showMemberNickname\x88\x01\x01B\x11\n" +
	"\x0f_group_nicknameB\x17\n" +
	"\x15_show_member_nickname\"\x92\x01\n" +
	"\vGroupStatus\x12\x1e\n" +
	"\bis_muted\x18\x01 \x01(\bH\x00R\aisMuted\x88\x01\x01\x12 \n" +
	"\tis_topped\x18\x02 \x01(\bH\x01R\bisTopped\x88\x01\x01\x12\x1b\n" +
	"\x06remark\x18\x03 \x01(\tH\x02R\x06remark\x88\x01\x01B\v\n" +
	"\t_is_mutedB\f\n" +
	"\n" +
	"_is_toppedB\t\n" +
	"\a_remark\"j\n" +
	"\x0fGroupInvitation\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x01 \x01(\tR\tinviterId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"target_ids\x18\x03 \x03(\tR\ttargetIds\"v\n" +
	"\x15FriendApplyActionResp\x12\x1f\n" +
	"\vis_approved\x18\x01 \x01(\bR\n" +
	"isApproved\x12 \n" +
	"\vapplicantId\x18\x02 \x01(\tR\vapplicantId\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\tR\btargetId\"\x0e\n" +
	"\fRelationResp\"\x18\n" +
	"\x16FriendStatusUpdateResp\"z\n" +
	"\x15GroupInviteActionResp\x12\x1f\n" +
	"\vis_approved\x18\x01 \x01(\bR\n" +
	"isApproved\x12$\n" +
	"\rapplicationId\x18\x02 \x01(\tR\rapplicationId\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\tR\btargetId\"\x17\n" +
	"\x15GroupStatusUpdateResp\"\x17\n" +
	"\x15GroupMemberManageResp\"\x1e\n" +
	"\x1cGroupMemberSettingUpdateResp\"\x0f\n" +
	"\rGroupQuitResp\"\x15\n" +
	"\x13GroupInvitationResp\"(\n" +
	"\rFriendListReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x0eFriendListResp\x121\n" +
	"\vfriend_list\x18\x01 \x03(\v2\x10.social.UserInfoR\n" +
	"friendList\"l\n" +
	"\rGroupApplyReq\x12!\n" +
	"\fapplicant_id\x18\x01 \x01(\tR\vapplicantId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1b\n" +
	"\tgreet_msg\x18\x03 \x01(\tR\bgreetMsg\"J\n" +
	"\x0eGroupApplyResp\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\tR\aapplyId\x12\x1d\n" +
	"\n" +
	"apply_time\x18\x02 \x01(\x03R\tapplyTime\"m\n" +
	"\x10GroupApplyAction\x12\x19\n" +
	"\bapply_id\x18\x01 \x01(\tR\aapplyId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\tR\tmanagerId\x12\x1f\n" +
	"\vis_approved\x18\x03 \x01(\bR\n" +
	"isApproved\"y\n" +
	"\x14GroupApplyActionResp\x12\x1f\n" +
	"\vis_approved\x18\x01 \x01(\bR\n" +
	"isApproved\x12$\n" +
	"\rapplicationId\x18\x02 \x01(\tR\rapplicationId\x12\x1a\n" +
	"\btargetId\x18\x03 \x01(\tR\btargetId\"/\n" +
	"\x12GetGroupMembersReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"z\n" +
	"\fBaseUserInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\rR\x06gender\"?\n" +
	"\x13GetGroupMembersResp\x12(\n" +
	"\x04List\x18\x01 \x03(\v2\x14.social.BaseUserInfoR\x04List\"i\n" +
	"\x0eRemoveAdminReq\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\"\x11\n" +
	"\x0fRemoveAdminResp\"2\n" +
	"\x14HandleFriendApplyReq\x12\x1a\n" +
	"\btargetId\x18\x01 \x01(\tR\btargetId\"\x17\n" +
	"\x15HandleFriendApplyResp\"x\n" +
	"\x12FriendStatusUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\x12,\n" +
	"\x06status\x18\x03 \x01(\v2\x14.social.FriendStatusR\x06status\"s\n" +
	"\x14GroupCreationRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\tR\tcreatorId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1d\n" +
	"\n" +
	"member_ids\x18\x03 \x03(\tR\tmemberIds\"\x9d\x01\n" +
	"\x11GroupMemberManage\x12\x1f\n" +
	"\voperator_id\x18\x01 \x01(\tR\n" +
	"operatorId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\tR\btargetId\x12/\n" +
	"\x06action\x18\x04 \x01(\x0e2\x17.social.GroupPermissionR\x06action\"Q\n" +
	"\x11GroupInviteAction\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\x12\x1f\n" +
	"\vis_accepted\x18\x02 \x01(\bR\n" +
	"isAccepted\"t\n" +
	"\x11GroupStatusUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12+\n" +
	"\x06status\x18\x03 \x01(\v2\x13.social.GroupStatusR\x06status\"\x84\x01\n" +
	"\x18GroupMemberSettingUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x124\n" +
	"\asetting\x18\x03 \x01(\v2\x1a.social.GroupMemberSettingR\asetting\"C\n" +
	"\x0fRelationRequest\x12\x19\n" +
	"\bfrom_uid\x18\x01 \x01(\tR\afromUid\x12\x15\n" +
	"\x06to_uid\x18\x02 \x01(\tR\x05toUid\"F\n" +
	"\x10GroupQuitRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"I\n" +
	"\x11FriendInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"F\n" +
	"\x10GroupInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"\t\n" +
	"\aPingReq\"\x1c\n" +
	"\bPingResp\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg*;\n" +
	"\x0fGroupPermission\x12\b\n" +
	"\x04KICK\x10\x00\x12\r\n" +
	"\tSET_ADMIN\x10\x01\x12\x0f\n" +
	"\vCHANGE_NAME\x10\x022\xb6\f\n" +
	"\rSocialService\x12F\n" +
	"\vApplyFriend\x12\x1a.social.FriendApplyRequest\x1a\x1b.social.FriendApplyResponse\x12M\n" +
	"\x11HandleFriendApply\x12\x19.social.FriendApplyAction\x1a\x1d.social.FriendApplyActionResp\x12=\n" +
	"\fDeleteFriend\x12\x17.social.RelationRequest\x1a\x14.social.RelationResp\x12P\n" +
	"\x12UpdateFriendStatus\x12\x1a.social.FriendStatusUpdate\x1a\x1e.social.FriendStatusUpdateResp\x12<\n" +
	"\rGetFriendInfo\x12\x19.social.FriendInfoRequest\x1a\x10.social.UserInfo\x12>\n" +
	"\rGetFriendList\x12\x15.social.FriendListReq\x1a\x16.social.FriendListResp\x12M\n" +
	"\x12GetFriendApplyList\x12\x1a.social.FriendApplyListReq\x1a\x1b.social.FriendApplyListResp\x12U\n" +
	"\x18GetHandleFriendApplyList\x12\x1c.social.HandleFriendApplyReq\x1a\x1b.social.FriendApplyListResp\x12>\n" +
	"\vCreateGroup\x12\x1c.social.GroupCreationRequest\x1a\x11.social.GroupInfo\x12<\n" +
	"\tQuitGroup\x12\x18.social.GroupQuitRequest\x1a\x15.social.GroupQuitResp\x12E\n" +
	"\rInviteToGroup\x12\x17.social.GroupInvitation\x1a\x1b.social.GroupInvitationResp\x12M\n" +
	"\x11HandleGroupInvite\x12\x19.social.GroupInviteAction\x1a\x1d.social.GroupInviteActionResp\x12;\n" +
	"\n" +
	"ApplyGroup\x12\x15.social.GroupApplyReq\x1a\x16.social.GroupApplyResp\x12J\n" +
	"\x10HandleGroupApply\x12\x18.social.GroupApplyAction\x1a\x1c.social.GroupApplyActionResp\x12M\n" +
	"\x11UpdateGroupStatus\x12\x19.social.GroupStatusUpdate\x1a\x1d.social.GroupStatusUpdateResp\x12M\n" +
	"\x11ManageGroupMember\x12\x19.social.GroupMemberManage\x1a\x1d.social.GroupMemberManageResp\x12>\n" +
	"\vRemoveAdmin\x12\x16.social.RemoveAdminReq\x1a\x17.social.RemoveAdminResp\x12;\n" +
	"\fGetGroupInfo\x12\x18.social.GroupInfoRequest\x1a\x11.social.GroupInfo\x12J\n" +
	"\x0fGetGroupMembers\x12\x1a.social.GetGroupMembersReq\x1a\x1b.social.GetGroupMembersResp\x12I\n" +
	"\x0eGetGroupAdmins\x12\x1a.social.GetGroupMembersReq\x1a\x1b.social.GetGroupMembersResp\x12_\n" +
	"\x15SetGroupMemberSetting\x12 .social.GroupMemberSettingUpdate\x1a$.social.GroupMemberSettingUpdateResp\x12)\n" +
	"\x04Ping\x12\x0f.social.PingReq\x1a\x10.social.PingRespB\n" +
	"Z\b./socialb\x06proto3"

var (
	file_apps_social_rpc_social_proto_rawDescOnce sync.Once
	file_apps_social_rpc_social_proto_rawDescData []byte
)

func file_apps_social_rpc_social_proto_rawDescGZIP() []byte {
	file_apps_social_rpc_social_proto_rawDescOnce.Do(func() {
		file_apps_social_rpc_social_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_social_rpc_social_proto_rawDesc), len(file_apps_social_rpc_social_proto_rawDesc)))
	})
	return file_apps_social_rpc_social_proto_rawDescData
}

var file_apps_social_rpc_social_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_apps_social_rpc_social_proto_msgTypes = make([]protoimpl.MessageInfo, 47)
var file_apps_social_rpc_social_proto_goTypes = []any{
	(GroupPermission)(0),                 // 0: social.GroupPermission
	(*UserInfo)(nil),                     // 1: social.UserInfo
	(*GroupInfo)(nil),                    // 2: social.GroupInfo
	(*FriendStatusInfo)(nil),             // 3: social.FriendStatusInfo
	(*FriendStatus)(nil),                 // 4: social.FriendStatus
	(*FriendApplyRequest)(nil),           // 5: social.FriendApplyRequest
	(*FriendApplyResponse)(nil),          // 6: social.FriendApplyResponse
	(*FriendApplyListReq)(nil),           // 7: social.FriendApplyListReq
	(*FriendApplyResp)(nil),              // 8: social.FriendApplyResp
	(*FriendApplyListResp)(nil),          // 9: social.FriendApplyListResp
	(*FriendApplyAction)(nil),            // 10: social.FriendApplyAction
	(*GroupMemberSetting)(nil),           // 11: social.GroupMemberSetting
	(*GroupStatus)(nil),                  // 12: social.GroupStatus
	(*GroupInvitation)(nil),              // 13: social.GroupInvitation
	(*FriendApplyActionResp)(nil),        // 14: social.FriendApplyActionResp
	(*RelationResp)(nil),                 // 15: social.RelationResp
	(*FriendStatusUpdateResp)(nil),       // 16: social.FriendStatusUpdateResp
	(*GroupInviteActionResp)(nil),        // 17: social.GroupInviteActionResp
	(*GroupStatusUpdateResp)(nil),        // 18: social.GroupStatusUpdateResp
	(*GroupMemberManageResp)(nil),        // 19: social.GroupMemberManageResp
	(*GroupMemberSettingUpdateResp)(nil), // 20: social.GroupMemberSettingUpdateResp
	(*GroupQuitResp)(nil),                // 21: social.GroupQuitResp
	(*GroupInvitationResp)(nil),          // 22: social.GroupInvitationResp
	(*FriendListReq)(nil),                // 23: social.FriendListReq
	(*FriendListResp)(nil),               // 24: social.FriendListResp
	(*GroupApplyReq)(nil),                // 25: social.GroupApplyReq
	(*GroupApplyResp)(nil),               // 26: social.GroupApplyResp
	(*GroupApplyAction)(nil),             // 27: social.GroupApplyAction
	(*GroupApplyActionResp)(nil),         // 28: social.GroupApplyActionResp
	(*GetGroupMembersReq)(nil),           // 29: social.GetGroupMembersReq
	(*BaseUserInfo)(nil),                 // 30: social.BaseUserInfo
	(*GetGroupMembersResp)(nil),          // 31: social.GetGroupMembersResp
	(*RemoveAdminReq)(nil),               // 32: social.RemoveAdminReq
	(*RemoveAdminResp)(nil),              // 33: social.RemoveAdminResp
	(*HandleFriendApplyReq)(nil),         // 34: social.HandleFriendApplyReq
	(*HandleFriendApplyResp)(nil),        // 35: social.HandleFriendApplyResp
	(*FriendStatusUpdate)(nil),           // 36: social.FriendStatusUpdate
	(*GroupCreationRequest)(nil),         // 37: social.GroupCreationRequest
	(*GroupMemberManage)(nil),            // 38: social.GroupMemberManage
	(*GroupInviteAction)(nil),            // 39: social.GroupInviteAction
	(*GroupStatusUpdate)(nil),            // 40: social.GroupStatusUpdate
	(*GroupMemberSettingUpdate)(nil),     // 41: social.GroupMemberSettingUpdate
	(*RelationRequest)(nil),              // 42: social.RelationRequest
	(*GroupQuitRequest)(nil),             // 43: social.GroupQuitRequest
	(*FriendInfoRequest)(nil),            // 44: social.FriendInfoRequest
	(*GroupInfoRequest)(nil),             // 45: social.GroupInfoRequest
	(*PingReq)(nil),                      // 46: social.PingReq
	(*PingResp)(nil),                     // 47: social.PingResp
}
var file_apps_social_rpc_social_proto_depIdxs = []int32{
	3,  // 0: social.UserInfo.status:type_name -> social.FriendStatusInfo
	8,  // 1: social.FriendApplyListResp.List:type_name -> social.FriendApplyResp
	1,  // 2: social.FriendListResp.friend_list:type_name -> social.UserInfo
	30, // 3: social.GetGroupMembersResp.List:type_name -> social.BaseUserInfo
	4,  // 4: social.FriendStatusUpdate.status:type_name -> social.FriendStatus
	0,  // 5: social.GroupMemberManage.action:type_name -> social.GroupPermission
	12, // 6: social.GroupStatusUpdate.status:type_name -> social.GroupStatus
	11, // 7: social.GroupMemberSettingUpdate.setting:type_name -> social.GroupMemberSetting
	5,  // 8: social.SocialService.ApplyFriend:input_type -> social.FriendApplyRequest
	10, // 9: social.SocialService.HandleFriendApply:input_type -> social.FriendApplyAction
	42, // 10: social.SocialService.DeleteFriend:input_type -> social.RelationRequest
	36, // 11: social.SocialService.UpdateFriendStatus:input_type -> social.FriendStatusUpdate
	44, // 12: social.SocialService.GetFriendInfo:input_type -> social.FriendInfoRequest
	23, // 13: social.SocialService.GetFriendList:input_type -> social.FriendListReq
	7,  // 14: social.SocialService.GetFriendApplyList:input_type -> social.FriendApplyListReq
	34, // 15: social.SocialService.GetHandleFriendApplyList:input_type -> social.HandleFriendApplyReq
	37, // 16: social.SocialService.CreateGroup:input_type -> social.GroupCreationRequest
	43, // 17: social.SocialService.QuitGroup:input_type -> social.GroupQuitRequest
	13, // 18: social.SocialService.InviteToGroup:input_type -> social.GroupInvitation
	39, // 19: social.SocialService.HandleGroupInvite:input_type -> social.GroupInviteAction
	25, // 20: social.SocialService.ApplyGroup:input_type -> social.GroupApplyReq
	27, // 21: social.SocialService.HandleGroupApply:input_type -> social.GroupApplyAction
	40, // 22: social.SocialService.UpdateGroupStatus:input_type -> social.GroupStatusUpdate
	38, // 23: social.SocialService.ManageGroupMember:input_type -> social.GroupMemberManage
	32, // 24: social.SocialService.RemoveAdmin:input_type -> social.RemoveAdminReq
	45, // 25: social.SocialService.GetGroupInfo:input_type -> social.GroupInfoRequest
	29, // 26: social.SocialService.GetGroupMembers:input_type -> social.GetGroupMembersReq
	29, // 27: social.SocialService.GetGroupAdmins:input_type -> social.GetGroupMembersReq
	41, // 28: social.SocialService.SetGroupMemberSetting:input_type -> social.GroupMemberSettingUpdate
	46, // 29: social.SocialService.Ping:input_type -> social.PingReq
	6,  // 30: social.SocialService.ApplyFriend:output_type -> social.FriendApplyResponse
	14, // 31: social.SocialService.HandleFriendApply:output_type -> social.FriendApplyActionResp
	15, // 32: social.SocialService.DeleteFriend:output_type -> social.RelationResp
	16, // 33: social.SocialService.UpdateFriendStatus:output_type -> social.FriendStatusUpdateResp
	1,  // 34: social.SocialService.GetFriendInfo:output_type -> social.UserInfo
	24, // 35: social.SocialService.GetFriendList:output_type -> social.FriendListResp
	9,  // 36: social.SocialService.GetFriendApplyList:output_type -> social.FriendApplyListResp
	9,  // 37: social.SocialService.GetHandleFriendApplyList:output_type -> social.FriendApplyListResp
	2,  // 38: social.SocialService.CreateGroup:output_type -> social.GroupInfo
	21, // 39: social.SocialService.QuitGroup:output_type -> social.GroupQuitResp
	22, // 40: social.SocialService.InviteToGroup:output_type -> social.GroupInvitationResp
	17, // 41: social.SocialService.HandleGroupInvite:output_type -> social.GroupInviteActionResp
	26, // 42: social.SocialService.ApplyGroup:output_type -> social.GroupApplyResp
	28, // 43: social.SocialService.HandleGroupApply:output_type -> social.GroupApplyActionResp
	18, // 44: social.SocialService.UpdateGroupStatus:output_type -> social.GroupStatusUpdateResp
	19, // 45: social.SocialService.ManageGroupMember:output_type -> social.GroupMemberManageResp
	33, // 46: social.SocialService.RemoveAdmin:output_type -> social.RemoveAdminResp
	2,  // 47: social.SocialService.GetGroupInfo:output_type -> social.GroupInfo
	31, // 48: social.SocialService.GetGroupMembers:output_type -> social.GetGroupMembersResp
	31, // 49: social.SocialService.GetGroupAdmins:output_type -> social.GetGroupMembersResp
	20, // 50: social.SocialService.SetGroupMemberSetting:output_type -> social.GroupMemberSettingUpdateResp
	47, // 51: social.SocialService.Ping:output_type -> social.PingResp
	30, // [30:52] is the sub-list for method output_type
	8,  // [8:30] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_apps_social_rpc_social_proto_init() }
func file_apps_social_rpc_social_proto_init() {
	if File_apps_social_rpc_social_proto != nil {
		return
	}
	file_apps_social_rpc_social_proto_msgTypes[3].OneofWrappers = []any{}
	file_apps_social_rpc_social_proto_msgTypes[10].OneofWrappers = []any{}
	file_apps_social_rpc_social_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_social_rpc_social_proto_rawDesc), len(file_apps_social_rpc_social_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   47,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_social_rpc_social_proto_goTypes,
		DependencyIndexes: file_apps_social_rpc_social_proto_depIdxs,
		EnumInfos:         file_apps_social_rpc_social_proto_enumTypes,
		MessageInfos:      file_apps_social_rpc_social_proto_msgTypes,
	}.Build()
	File_apps_social_rpc_social_proto = out.File
	file_apps_social_rpc_social_proto_goTypes = nil
	file_apps_social_rpc_social_proto_depIdxs = nil
}
